/*
 * EEPROM PARA VARIABLES WIFI DE 0 A 200
 * 0-LARGO DE SSID
 * 5-LARGO DE LA CONTRASEÑA
 * 10-ACTIVAR WIFI ?
 * 15-NOMBRE DE SSID
 * DESDE DONDE TERMINA NOMBRE SSID + 5 - CONTRASEÑA
 * ESPACIOS PARA VARIABLES DE SENSOR DE 201 A 420
 * 205-SET POINT
 * 215-Histeresis POSITIVA
 * 225-Histeresis NEGATIVA
 * 235-INTERVALO DE LECTURA
 * 245-UNIDAD METRICA DE LECTURA(CELSIUS O FAHRENHEIT)
 * 
*/

/*
 * ESTRUCTURA DEL MENSAJE MQTT
 * POR AHORA DOS MENSAJES DIFERENTES
 * TIPO/ID/TEMPERATURA INTERIOR/TEMPERATURA EXTERIOR/OUT0/OUT1
 * 
 * TIPO/ID/NOMBRE/UBICACION/SETPOINT/Histeresis POSITIVA/Histeresis NEGATIVA
 * 
 * 
*/
