/*
 * EEPROM PARA VARIABLES WIFI DE 0 A 200
 * 005 = SSID
 * 050 = CONTRASEÑA
 * 090 = LARGO SSID
 * 095 = LARGO CONTRASEÑA
 * 100 = WIFI ACTIVO -BOLEANO
 * 
 * ESPACIOS PARA VARIABLES DE SENSOR DE 201 A 420
 * 205 = SET POINT
 * 215 = Histeresis POSITIVA
 * 225 = Histeresis NEGATIVA
 * 235 = INTERVALO DE LECTURA
 * 245 = UNIDAD METRICA DE LECTURA(CELSIUS O FAHRENHEIT)
 * 255 = DIFERENCIAL PARA ALERTA DE ALTA TEMPERATURA
 * 265 = DIFERENCIAL PARA ALERAT DE BAJA TEMPERATURA
 * 
 * ESPACIOS PARA VARIABLES DE MEMORIA MICRO SD DE 450 A 500
 * 450 = ALGUNA VEZ HUBO UNA CONEXION A INTERNET -BOLEANO
 * 
*/

/*
 * ESTRUCTURA DEL MENSAJE MQTT
 * POR AHORA TRES MENSAJES DIFERENTES
 * TIPO/ID/TEMPERATURA INTERIOR/TEMPERATURA EXTERIOR/OUT0/OUT1--TIPO 10
 * 
 * TIPO/ID/NOMBRE/UBICACION/SETPOINT/Histeresis POSITIVA/Histeresis NEGATIVA/ALARMA SUPERIOR/ALARMA INFERIOR/METRICA --TIPO 20
 * 
 * TIPO/ID/TEMPERATURA GUARDADA EN SD--TIPO 30
 * 
*/
